# -*- coding: utf-8 -*-
"""random_training.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1od7m_wk3TnB5cdV94aI7FogxwEu6o7XV
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
df = pd.DataFrame()
df_1 = pd.DataFrame()

E1 = [0,0,1,1]
E2 = [0,1,0,1]
saida = [0.0,1.0,1.0,0.0]
tx = 0.0001

def manipular_peso_trash_hold(matriz):
  if matriz.shape[0] == 2:
    for i in range(matriz.shape[0]):
      for j in range(matriz.shape[1]):
        matriz[i][j] =  (matriz[i][j]*40) -20 
  else:
    for i in range(matriz.shape[0]):
      matriz[i] = (matriz[i]*40)-20

erro = 1.0
n = 0.0
while erro > tx:
  erro = 0.0
  saidas = []
  w1 = np.random.rand(2,3)
  w2 = np.random.rand(3)
  manipular_peso_trash_hold(w1)
  manipular_peso_trash_hold(w2)
  I = np.zeros((3,3))
  O = np.zeros((3,3))
  for i in range(len(E1)):
    #I1 - copia dos dados de entrada.
    I[0][0] = E1[i]
    I[0][1] = E2[i]
    I[0][2] = 1.0 # Constante.
    #Copia para os Outputs
    O[0][0] = I[0][0]
    O[0][1] = I[0][1]
    O[0][2] = I[0][2]
    #Calculo Para as entradas da segunda camada.
    I[1][0] = O[0][0]*w1[0][0] + O[0][1]*w1[0][1] + O[0][2]*w1[0][2]
    I[1][1] = O[0][0]*w1[1][0] + O[0][1]*w1[1][1] + O[0][2]*w1[1][2]
    I[1][2] = 1.0 # constante.
    #Calculo do Exp para trash_hold.
    O[1][0] = 1.0/(1.0+np.exp(-I[1][0]))
    O[1][1] = 1.0/(1.0+np.exp(-I[1][1]))
    O[1][2] = I[1][2]
    #calculo da ultima entrada
    I[2][0] = O[1][0]*w2[0] + O[1][1]*w2[1] + O[1][2]*w2[2]
    #Calculo da ultima saida
    O[2][0] = 1.0/(1.0+np.exp(-I[2][0]))
    erro += float(pow((saida[i]-O[2][0]),2))
    saidas.append(O[2][0])
  n+=1
  erro*=0.5
  print(f'época: {n: .1f} erro: {erro: .4f}')

print("Epoca: " + str(n))
print("Erro: " + str(erro))
peso1 = []
peso2 = []
peso3 = []
for i in range(w1.shape[1]):
  peso1.append(w1[0][i])
  peso2.append(w1[1][i])
  peso3.append(w2[i])
df_1['W0'] = peso1
df_1['W1'] = peso2
df_1['W2'] = peso3
df_1

df['E1'] = E1
df['E2'] = E2
df['Saidas_esperadas'] = saida
df['Saidas_geradas'] = saidas
df